### ISSUE TITLE
UnicodeDecodeError running receive.grc example on Radioconda

### ISSUE THREAD

**Issue by n7ihq** [daniestevez/gr-hermeslite2#7]
I installed MacOS Radioconda version 2023.11.06 with python 3.11.6 and gnuradio 3.10.8. Running example receive.grc produces the following UnicodeDecodeError:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/jim/radioconda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner                                                                                        
    self.run()
  File "/Users/jim/radioconda/lib/python3.11/site-packages/gnuradio/grc/gui/Executor.py", line 115, in run                                                                        
    r = self.process.stdout.read(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 142: invalid continuation byte

Note: This error does not occur running receive.grc on Raspberry Pi 4 Bookworm OS with python3 3.11.2 and gnuradio 3.10.8.

**Comment by daniestevez** [comment]
I think this is more likely to be an issue with GNU Radio rather than gr-hermeslite2. It might still be the case that `receive.py` is generating non-UTF-8 data in stdout and this makes GNU Radio companion choke on Mac OS. I would suggest that you:
1. Open an issue in the gnuradio repo.
2. Try to run `receive.py` in Mac OS to see if it prints out anything strange to stdout (you might want to redirect stdout to a file and look at it with a hex editor).

**Comment by n7ihq** [comment]
The gr-hermeslite2 module works perfectly on Debian 12 Bookworm with python 3.11.2 and gnuradio 3.10.5. I will investigate the issue with MacOS and Radioconda.
